dataset:
  dataset_path: /root/llama-sql-v4/text-to-sql-v1-easy
model:
  model_id: meta-llama/Llama-2-7b-chat-hf
  peft_config:
    lora_alpha: 16
    lora_dropout: 0.1
    r: 64
    task_type: CAUSAL_LM
  quantization_config:
    bnb_4bit_compute_dtype: float16
    bnb_4bit_quant_type: nf4
    bnb_4bit_use_double_quant: true
    llm_int8_enable_fp32_cpu_offload: true
    llm_int8_has_fp16_weight: true
    llm_int8_threshold: 6.0
    load_in_4bit: true
    load_in_8bit: false
model_output: ./output/exp_1.0_model
tokenizer:
  tokenizer_config:
    max_length: 2048
    padding: true
    truncation: true
train_config:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-08
  bf16: true
  dataloader_drop_last: true
  deepspeed:
    communication_data_type: fp16
    gradient_accumulation_steps: auto
    gradient_clipping: auto
    train_batch_size: auto
    train_micro_batch_size_per_gpu: auto
    zero_optimization:
      allgather_bucket_size: 500000000.0
      allgather_partitions: true
      contiguous_gradients: true
      offload_optimizer:
        device: cpu
        pin_memory: true
      overlap_comm: true
      reduce_bucket_size: 500000000.0
      reduce_scatter: true
      round_robin_gradients: true
      stage: 2
  eval_steps: 1
  evaluation_strategy: 'no'
  gradient_accumulation_steps: 16
  greater_is_better: false
  learning_rate: 0.0002
  load_best_model_at_end: true
  logging_steps: 1
  logging_strategy: 'no'
  max_grad_norm: 1
  max_steps: 5
  metric_for_best_model: eval_loss
  output_dir: ./output/exp_2.0
  per_device_eval_batch_size: 1
  per_device_train_batch_size: 1
  report_to: wandb
  run_name: exp_2.0
  save_steps: 10
  save_strategy: 'no'
  weight_decay: 0.01
